name: TABSHILLA'S PORTFOLIO

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: tabshilla/tabshilla-portfolio:latest
        cache-from: type=registry,ref=tabshilla/tabshilla-portfolio:latest
        cache-to: type=inline
          
    - name: Deploy to Render
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
            
    - name: Verify Deployment
      run: |
        echo "Deployment initiated. Please check your Render dashboard for the status."
        echo "Note: It may take a few minutes for the changes to propagate."